### ISSUE TITLE
Failed to create some screenshots for https

### ISSUE THREAD

**Issue by dmsoft** [vbauer/manet#15]
For example, please have a look at the following link 
https://manet.herokuapp.com/?url=https%3A%2F%2Fforums.mozilla.org%2Findex.php&format=jpg&force=true

Though it works ok for 
https://manet.herokuapp.com/?url=https%3A%2F%2Fmicrosoft.com&format=jpg&force=true
 
How to forcefully switch off certificate check when making request to resource ?

**Comment by vbauer** [comment]
I've just tried to reproduce this ticket locally and it works fine for me.

Have you tried to:
* change engine (phantomjs/slimerjs)
* update phantomjs/slimerjs
?

**Comment by dmsoft** [comment]
When I change engine to slimerjs on my dev OSX it works perfectly. 
But I didn't find the way to make slimerjs workable on hosting CentOS 5. Though it doesn't throw any errors. Screenshots are not generated both for http and https web sites. 
Probably the problem is the absence of correct xvfb-run file after xvfb installation. I've got xvfb-run.sh file somewhere and put to the system manually.

**Comment by dmsoft** [comment]
Solved: 
Just change commands for starting phantomjs to something like 
phantomjs": {
            "linux": "phantomjs --ignore-ssl-errors=yes --ssl-protocol=any",....
  in config/default.json

**Comment by vbauer** [comment]
Great. :)
