### ISSUE TITLE
Viewport Height Error

### ISSUE THREAD

**Issue by alexphelps** [vbauer/manet#19]
I've tried to set the Viewport Height a dozen ways and can't get it to work. Is there something I'm doing wrong?

https://manet.herokuapp.com/?url=www.prontomarketing.com&width=1280&height=1000

How can I set the Viewport Height?

**Comment by vbauer** [comment]
Yes, I faced with this problem and I still do not understand it. SlimerJS engine doesn't have this issue, so you can switch on it, or just use the following workaround: https://manet.herokuapp.com/?url=www.prontomarketing.com&clipRect=1,1,1280,1000

**Comment by vbauer** [comment]
I suggest to close it for now, because we can use `clipRect` parameter to resolve this issue.
