### ISSUE TITLE
documentation issue regarding the --cache parameter?

### ISSUE THREAD

**Issue by jfix** [vbauer/manet#20]
in the readme it says regarding the ```--cache``` parameter that one can set it to a 'no-positive value' in order to effectively disable the cache.

when trying to do this, like so:

```
$ /usr/local/bin/manet --port 3001 --cache -1
error: Cache life time must be a number
```

it appears that this is not actually possible. For testing it would actually be quite nice to disable the cache.

**Comment by vbauer** [comment]
@jfix Thank you for found mistake, I've just fixed it. Now, negative value could be used to switch off cache mechanism and FS watchdog.

Unfortunately, I found a bug with negative numbers in `joi` library and created an issue https://github.com/hapijs/joi/issues/558

Workaround:
```bash
$ /usr/local/bin/manet --port 3001 --cache=-1
```
