### ISSUE TITLE
size of screenshots is huge!

### ISSUE THREAD

**Issue by jfix** [vbauer/manet#21]
[This might be a duplicate of #14]

Me again. I've noticed that screenshots taken with manet are huge, size-wise. For example, the Google homepage, as a screenshot is about 3 MB in size (see screenshot of the screenshot below). Others go easily to 8 MB and beyond. manet was started like this:

```forever start -a -l ~/manet.log -o ~/manet.out -e ~/manet.err /usr/local/bin/manet --port 3000 --engine phantomjs```

In comparison, screenshot-as-a-service (from here: https://github.com/fzaninotto/screenshot-as-a-service) produces screenshots of only a couple of hundred kilobytes, and their quality are comparable.

Any idea what I could change to decrease the size? I'm using the option ```quality=0``` but that hasn't had any impact on size. I've also tried changing the engines (phantomjs vs slimerjs) but I don't see a difference either.

Thanks for your help in advance.

![screen shot 2015-02-20 at 10 07 15](https://cloud.githubusercontent.com/assets/170240/6283800/559ca5da-b8e9-11e4-8b57-68fa42b20375.png)

**Comment by vbauer** [comment]
Please see comments from https://github.com/vbauer/manet/issues/14
If you have any questions or objections, just re-open this issue.
