### ISSUE TITLE
problem with some weird redirected URLs (BBC)

### ISSUE THREAD

**Issue by jfix** [vbauer/manet#23]
Hello, I'm noticing some weird redirects with URLs from the BBC:

At least from my location, in France, when I attempt to go here http://www.bbc.co.uk/news/business-31599492 I get redirected to http://www.bbc.com/news/business-31599492. However it's not a classic redirect (301 or 302), the web inspector in Chrome doesn't show this redirect, but ends up with the .com page.

Now, how does this concern manet? Well using manet, I don't get a screenshot, but a 404.  Not sure that something can be done on manet's level, but I would still be interested?

Thanks,
Jakob.

**Comment by vbauer** [comment]
It looks like there is an open bug in PhantomJS: https://github.com/ariya/phantomjs/issues/10389
Unfortunately, I couldn't check it now with SlimerJS. I'll try it asap.

**Comment by jfix** [comment]
@vbauer thanks for following this up.  As suggested over there, adding a delay (I used 5000 msec, just to be sure) actually works in this particular case. As I'm not after real-time synchronous screenshots, that's a feasible workaround for me.

**Comment by vbauer** [comment]
I've just tried to investigate this problem and found a possible solution: [--ignore-ssl-errors](http://phantomjs.org/api/command-line.html).

If it doesn't help, could you please try to add "--ssl-protocol=tlsv1" in the `config/default.json`

**Comment by jfix** [comment]
Sorry for the delay of my response. I just tried with the new configuration option (I tried both actually, first ```--ignore-ssl-errors=true``` then in addition also ```--ssl-protocol=tlsv1```), but the results are non-conclusive:

```
info: Capture site screenshot: www.bbc.co.uk/news/business-31599492
error: Error while sending file: ENOENT, stat '/tmp/eyJ1cmwiOiJodHRwOi8vd3d3LmJiYy5jby51ay9uZXdzL2J1c2luZXNzLTMxNTk5NDkyIn0=.png'
```

I tried with both the protocol ```http://``` and without, just to make sure I also tried just ```google.com``` which confirmed that the manet installation itself is not broken...

Here is what Chrome sees, apparently it's a 404 ... hmmmm ....

![screen shot 2015-09-10 at 22 07 44](https://cloud.githubusercontent.com/assets/170240/9799593/74bad932-5808-11e5-8548-8cf8947c6103.png)

**Comment by vbauer** [comment]
@jfix Thank you for information. I've just fixed wrong HTTP status codes, but I still do not understand why it doesn't work..

**Comment by jfix** [comment]
@vbauer does it work for you?

cheers,
Jakob.

**Comment by vbauer** [comment]
@jfix Yesterday I committed possible workaround https://github.com/vbauer/manet/commit/a4dbc36bf1f36dbd9f96a4e2cdc101172f1122b5 and it worked, but today as I see it doesn't work. Strange..

**Comment by jfix** [comment]
Hmm, I just tried this additional option and it didn't change a thing, unfortunately. :-( Thanks for trying!

**Comment by vbauer** [comment]
Could you please try to test it with last commit (https://github.com/vbauer/manet/commit/5853aa6d526a555659891b76d8772a48aa03ae10)?

**Comment by vbauer** [comment]
JFYI: Now, it is possible to install the release version (0.4.4) to check it.

**Comment by jfix** [comment]
Thanks @vbauer, unfortunately I cannot currently test. If it works for you, then please close the issue. Once I'm able to pick this project up again, I will test and if necessary come back to this issue. Thanks a lot for this!
