### ISSUE TITLE
Heroku installation instructions?

### ISSUE THREAD

**Issue by marckohlbrugge** [vbauer/manet#24]
Would you mind sharing what's needed to get this running on Heroku? I'm not too familiar with Node.js, so any help is appreciated.

**Comment by vbauer** [comment]
Nothing special, Heroku script is already in project: Procfile
Additional information about be found here: https://devcenter.heroku.com/articles/deploying-nodejs (section "Deploy your application to Heroku")

**Comment by marckohlbrugge** [comment]
Thank you. That was indeed way easier than I expected.
