### ISSUE TITLE
Converting Web Pages with SVG elements

### ISSUE THREAD

**Issue by BrianSHenderson** [vbauer/manet#27]
When using PhantomJS the SVG elements appear to be converted into images although I understand PhantomJS can handle SVGs.  

How can I sort this out?

**Comment by vbauer** [comment]
Could you please provide a little bit more details? Do you have some problems with Manet or PhantomJS?

I've just tried to capture http://www.w3schools.com/html/html5_svg.asp and it works fine for me.
