### ISSUE TITLE
back ground color of some html element does not support by manet whe i try to generate pdf from web page

### ISSUE THREAD

**Issue by chandan-git** [vbauer/manet#38]
example:
<li class="color cdf7a20" style="white-space: nowrap; word-break: inherit;"><i class="fa fa-circle dots" style="color:#df7a20"></i><span style="color:#666666">Chandan</span></li>

for the above code i have found the issue.. please let me if i'm wrong

**Comment by vbauer** [comment]
I'm not sure that it is Manet issue (probably you found some bug in PhantomJS), but could you please provide me URL which I can test?

**Comment by chandan-git** [comment]
thanks for the reply. Actually the website has not been published or deployed yet in cloud so i'm sorry i cant provide u that. your comment is really helpful to me and i appreciate it.

**Comment by chandan-git** [comment]
hi,
is it possible in manet to add color in a div element and save that as it was in pdf.

**Comment by vbauer** [comment]
You can try to change this line to add your custom CSS: https://github.com/vbauer/manet/blob/master/src/scripts/screenshot.js#L16

At the current moment, you haven't got any other option to configure custom styles.

**Comment by chandan-git** [comment]
thanks.. and let me check this once..
