### ISSUE TITLE
Api key or other security mechanism?

### ISSUE THREAD

**Issue by jeff1985** [vbauer/manet#41]
Is there an easy way to secure the webservice with an api key or username/password? 
I feel very uncomfortable by exposing the control over a fully functional webbrowser to anyone who is smart enough to guess the port number...

**Comment by vbauer** [comment]
I've just added support of "Basic" auth (https://github.com/vbauer/manet/commit/da8048fecaa69fda050ff1a0c17f41c4eb0445df), you can add another security mechanism. I'm open for pull requests.

In the nearest future I'll update README and add more unit tests.

**Comment by jeff1985** [comment]
Wow thats great! Basic auth is absolutely enough for my purposes. 
Will the new version be available with npm soon or will i need to build from source?

**Comment by vbauer** [comment]
I hope release 0.4.6 will be ready before the end of this week.

**Comment by jeff1985** [comment]
ok, thats great!

**Comment by vbauer** [comment]
@jeff1985 NP :)

**Comment by vbauer** [comment]
@jeff1985 0.4.6 version has been released.

**JFYI**: Minimum version of NodeJS is 4.0.
