### ISSUE TITLE
heroku and phantomjs2

### ISSUE THREAD

**Issue by ioRekz** [vbauer/manet#42]
Are you able to deploy to heroku with phantomjs2 in Procfile ?

**Comment by vbauer** [comment]
@ioRekz Actually, I've never tried to do it. Have you tried to use https://github.com/srbartlett/heroku-buildpack-phantomjs-2.0 ? Maybe it will help with this issue.

**Comment by vbauer** [comment]
Apparently the ticket is no longer relevant and could be closed
