### ISSUE TITLE
callback not working with php_fastcgi because of missing content-length header

### ISSUE THREAD

**Issue by jeff1985** [vbauer/manet#45]
Hi!

I'm trying to implement a php application that will be receiving screenshots generated by manet. I've faced difficulties receiving the screenshots with the callback url. 

My logs show:
> [Fri Nov 20 01:15:29 2015] [error] [client 127.0.0.1] chunked Transfer-Encoding forbidden: /php5-fcgi/index.php

From my understanding this is because you stream the file directly to the POST request without specifying the content length. 
> fileStream.pipe(request.post(callbackUrl, (err) => {
>                if (err) {
>                    sendError(res, 'Error while streaming image file: ' + err.message);
>                }
>                onImageFileSent(file, config);
>            }));

For me this means that i'm not able to use the callback function for my php application.
Can you please add a Content-Length header?

**Comment by vbauer** [comment]
Thank you for information, I've just fixed it.
