### ISSUE TITLE
How to serve manet not at the root of a web domain?

### ISSUE THREAD

**Issue by boogheta** [vbauer/manet#54]
Hi,

We're trying to install Manet for use on one of our servers without having to setup a new subdomain for it nor opening a port to the whole world.

So we were basically just using apache's ReverseProxy to serve manet's port onto a url such as http://www.example.com/manet

It works perfectly for the API part, unfortunately it looks like the code for the web ui is only meant for the app to be served at the baseroot of the domain: the css and js are not found and the open button redirects to root urls

**Comment by bverjat** [comment]
+1

**Comment by vbauer** [comment]
@boogheta Hello, I hope, I've just fixed this problem. Could you please check it with the master branch? If everything is fine - just write me back and I make a new hot-fix release.

**Comment by boogheta** [comment]
Looks fine, yes! Thanks @vbauer !

**Comment by vbauer** [comment]
@boogheta No problem, you're welcome. )

**Comment by boogheta** [comment]
Please let me know when it is updated in npm so I can update your install which was installed using npm -g :)

**Comment by vbauer** [comment]
Sorry for delay, I've just released version 0.4.13.
