### ISSUE TITLE
ddos protected websites

### ISSUE THREAD

**Issue by diridam** [vbauer/manet#60]
Hi, 
I'm trying to get in prod manet for a listing website and i'm having trouble on ddos protected websites (cloudflare and other cookie based protection techniques). 
is there any handler that reads the initial cookie and then returns it back to the request in order to bypass the protection?

thanks

**Comment by vbauer** [comment]
@diridam Manet doesn't have such feature, but I'm opened for pull requests. :)

**Comment by vbauer** [comment]
New info:

You can configure cookies using corresponding parameters (but you need to pass them to Manet manually in request)
