### ISSUE TITLE
Add ability to crop image

### ISSUE THREAD

**Issue by mgleis** [vbauer/manet#7]
It would be great to have image cropping built in.

**Comment by iwanowskidev** [comment]
For example:
https://manet.herokuapp.com/?url=www.google.com&width=1024&clipRect=0%2C0%2C1024%2C2000

I get a screen like

![image](https://user-images.githubusercontent.com/38204363/55560729-25098a00-56f1-11e9-964c-cca4dbb04933.png)

out of page should not be included in a screenshot

Purpose of crop option is diferent. Smaler image size is preferable.

I want to do screnshot of maximum dimension 1024x2000.
How could I achive this scenario?

I want something like the maximum height of the viewport
