### ISSUE TITLE
Provide disk-cache support

### ISSUE THREAD

**Issue by nathandunn** [vbauer/manet#84]
phantomjs caches javascript files using the ```disk-cache``` parameter:  http://phantomjs.org/api/command-line.html

```--disk-cache=[true|false] enables disk cache (at desktop services cache storage location, default is false). Also accepted: [yes|no].```

I would like to be able to turn this on.

**Comment by aubergene** [comment]
You add command flags as part of the phantomjs command in default.yaml

**Comment by nathandunn** [comment]
I see it now in the documentation.  Thanks.
